server:
  port: 8080
  shutdown: graceful
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json,application/xml
    min-response-size: 1024

spring:
  application:
    name: nurture-server

management:
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

