server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json,application/xml
    min-response-size: 1024

spring:
  application:
    name: nurture-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
