spring:
  jpa:
    properties:
      hibernate:
        default_schema: nurture
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          formate_sql: true
  #    database-platform: org.hibernate.dialect.SQLServerDialect
  datasource:
    url: jdbc:sqlserver://balasha.database.windows.net:1433;database=balasha;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ENC(isMGczlZkJogODlLLqOfK3nXikOliE6rq5xvNRvLoRim9SqcuBQHLtmAG+Db6jSh)
    password: ENC(ih3aALbDlifLBsxd4r6k9pkfa1PaRJQlpgAHBhQAZy0eGHCrLRmJG/CMmuc7h2cJNPAK4A7VBrCSDlJ1jQac/g==)
  sql:
    init:
      mode: always
